### ISSUE TITLE
Where I should place the file proxy.txt and which name i should give it?

### ISSUE THREAD

**Issue by giuseppe99barchetta** [crinny/teleboost#1]
Hi,

Thanks for your work!  

Where I should place the file proxy.txt and which name i should give it?

**Comment by crinny** [comment]
You can place it in whatever place you want with any name, just be sure to use an absolute path when running teleboost

**Comment by giuseppe99barchetta** [comment]
Where i can take good proxies?

**Comment by crinny** [comment]
It works with any socks/https ipv4/6 proxies. Ipv6 proxies are usually cheaper so you might want to search for those
