### ISSUE TITLE
Invalid URL: host is required for absolute urls

### ISSUE THREAD

**Issue by Tolly2991** [crinny/teleboost#10]
Hi all, sorry that I'm asking might it a stupid question but I really want to try your soft but I can't,  I've got this issue already second time I reinstalled ubuntu already but still got this. 
<img width="1279" alt="Screenshot 2020-11-22 at 17 16 43" src="https://user-images.githubusercontent.com/27013370/99910655-23863e80-2ce7-11eb-882f-ed759c945115.png">
<img width="1279" alt="Screenshot 2020-11-22 at 17 17 27" src="https://user-images.githubusercontent.com/27013370/99910657-284af280-2ce7-11eb-9416-1123b0767e8a.png">

**Comment by crinny** [comment]
The proxy format is `http://login:pass@ip:port` (you don't need @ if the proxy doesn't require authorization), in your proxy list there is a misplaced `:` character after each `http://`.

**Comment by Tolly2991** [comment]
yore right cheers! take care yourself!!
