### ISSUE TITLE
Ошибка при загрузке прокси

### ISSUE THREAD

**Issue by batiscuff** [crinny/teleboost#2]
Здравствуйте! Возможно немного неправильное название для темы, но всё же.

Столкнулся с проблемой: 
```
at ~/.local/lib/python3.8/site-packages/yarl/_url.py:161 in __new__

ValueError
Invalid URL: host is required for absolute urls
```
Когда файл **proxy.txt** форматирую вручную - всё ок. Как только использовал для форматирования python-скрипт - всё отказалось работать.

Вот код скрипта:
```
def main():
    new_content = ""
    with open("proxy.txt", "r", encoding="utf-8") as p:
        for line in p:
            line.strip()
            new_line = "http://@" + line
            new_content += new_line

    with open("proxy.txt", "w+", encoding="utf-8") as w:
        w.write(new_content)


if __name__ == "__main__":
    main()
```
На выходе получается такой прокси: **http://@115.209.173.174:3000**
UPD: пробовал формат **http://:@115.209.173.174:3000** - безуспешно

**Comment by crinny** [comment]
Формат прокси: `http://login:pass@ip:port`, если прокси без авторизации, то первая часть вместе с @ не нужна

**Comment by batiscuff** [comment]
Спасибо! Заработало 👍🏼
