### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by NoNameoN-A** [crinny/teleboost#7]
When i start
`python -m teleboost  view [https://t.me/background_photos_new/40] [ProxyList.txt]`
I have 
`Too many arguments`

**Comment by crinny** [comment]
You have to pass proxies using a `-p` option:
```sh
python -m teleboost view https://t.me/background_photos_new/40 -p ProxyList.txt
```

**Comment by NoNameoN-A** [comment]
Ok thanks and this is the correct output?

> Alessandro Greco
> Sito Web:[www.nonameon.altervista.org/](http://nonameon.altervista.org/)
> Interessati:www.interessati.com
> Telefono: +39 327 83 21 517
> Whatsapp: NO | Signal: SI
