### ISSUE TITLE
not find a version that satisfies the requirement teleboost

### ISSUE THREAD

**Issue by Tolly2991** [crinny/teleboost#9]
Hi all, Impressive commit!!! I'm trying to install that on my ubuntu but I always get this issue. why? 

Could not find a version that satisfies the requirement teleboost (from versions: )
No matching distribution found for teleboost

**Comment by crinny** [comment]
Make sure you are using the right Python version (3.7+) when installing. Run this command to check it:
```sh
pip --version
```
On Linux, you might need to replace `pip` with `pip3` in order for it to work.

**Comment by Tolly2991** [comment]
Thanks a million youre the best!!!
